### ISSUE TITLE
No module named 'openwisp_users.api.mixins'

### ISSUE THREAD

**Issue by manusysadmin** [openwisp/openwisp-ipam#91]
python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "C:\python\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\python\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    django.setup()
  File "C:\python\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\python\lib\site-packages\django\apps\registry.py", line 122, in populate
    app_config.ready()
  File "C:\python\lib\site-packages\django\contrib\admin\apps.py", line 24, in ready
    self.module.autodiscover()
  File "C:\python\lib\site-packages\django\contrib\admin\__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "C:\python\lib\site-packages\django\utils\module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "C:\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\manusysadmin\desktop\myplayground\web-projects\openwisp-ipam\openwisp_ipam\admin.py", line 18, in <module>
    from .api.views import HostsSet
  File "c:\users\manusysadmin\desktop\myplayground\web-projects\openwisp-ipam\openwisp_ipam\api\views.py", line 9, in <module>
    from openwisp_users.api.mixins import FilterByOrganizationManaged, FilterByParentManaged
ModuleNotFoundError: No module named 'openwisp_users.api.mixins'

**Comment by ManishShah120** [comment]
Hi, @manusysadmin 
Try `pip install openwisp-users` or `pip install -U https://github.com/openwisp/openwisp-users/archive/master.zip` , may be it requires some of the dependencies of openwisp-users which are not being released yet.

**Comment by nemesisdesign** [comment]
@ManishShah120 is correct, see: https://github.com/openwisp/openwisp-ipam/blob/master/requirements.txt#L2

**Comment by manusysadmin** [comment]
> Hi, @manusysadmin
> Try `pip install openwisp-users` or `pip install -U https://github.com/openwisp/openwisp-users/archive/master.zip` , may be it requires some of the dependencies of openwisp-users which are not being released yet.

**Comment by manusysadmin** [comment]
@ManishShah120 , Thank you very much for the suggestion it was very helpful for me and unblocked me.
